self-hosted-runner:
  # Labels of self-hosted runner in array of strings.
  labels:
    - atom-mi35x-8gpu-oot-acc
    - atom-mi355-8gpu.predownload
    - atom-mi355-8gpu-aac-runner
    - atom-mi355-8gpu-vllm-sgl-ci
    - spur-runner-mi355x-8gpu
    - atom-mi308-8gpu-plugins-accuracy
    - atom-mi308-8gpu-plugins-benchmark
    - atom-mi308-8gpu-vllm-sgl-ci
    - atom-plugin-acc-validation-runner-vllm
    - atom-plugin-acc-validation-runner-sgl
    - build-only-atom
    - linux-atom-do-mi350x-8
    - linux-atom-mi35x-1
    - linux-atom-mi35x-4
    - linux-atom-mi355-1
    - linux-atom-mi355-4
    - linux-atom-mi355-8

# Configuration variables in array of strings defined in your repository or
# organization. `null` means disabling configuration variables check.
# Empty array means no configuration variable is allowed.
config-variables: null

# Configuration for file paths. The keys are glob patterns to match to file
# paths relative to the repository root. The values are the configurations for
# the file paths. Note that the path separator is always '/'.
# The following configurations are available.
#
# "ignore" is an array of regular expression patterns. Matched error messages
# are ignored. This is similar to the "-ignore" command line option.
paths:
  .github/workflows/*.yml:
    ignore:
      - 'maximum number of inputs for "workflow_dispatch" event is 10 but [0-9]+ inputs are provided'

  .github/workflows/*.yaml:
    ignore:
      - 'maximum number of inputs for "workflow_dispatch" event is 10 but [0-9]+ inputs are provided'

  .github/workflows/atom-vllm-accuracy-validation.yaml:
    ignore:
      - '"steps" section is missing in job "oot-model-accuracy-priority-[0-9]+"'
      - '"steps" section must be sequence node but got alias node'
